### ISSUE TITLE
Any chance to update latest meeting sdk  v5.7.1 

### ISSUE THREAD

**Issue by mirkarpude** [driftboat/flutter_zoom#9]
feature Request

Or v5.5.1

**Comment by driftboat** [comment]
Thanks for reaching out，that’s a great question

**Comment by driftboat** [comment]
flutter_zoom 1.0.3(with zoom-sdk-android-5.7.1.1268 and  zoom-sdk-ios-5.7.1.645) has been published.

**Comment by mirkarpude** [comment]
How to set meeting_views_options
like
 opts.meeting_views_options = MeetingViewsOptions.NO_TEXT_PASSWORD+MeetingViewsOptions.NO_TEXT_MEETING_ID + MeetingViewsOptions.NO_BUTTON_PARTICIPANTS

**Comment by pinskynet** [comment]
Launching lib/main.dart on iPhone 6 in debug mode...
lib/main.dart:1
Xcode build done.                                            3.8s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[10227]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1fed8fb78) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10c4e42c8). One of the two will be used. Which one is undefined.
    objc[10227]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1fed8fbc8) and /System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x10c4e4318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    warning: [CP] Unable to find matching .xcframework slice in 'ios-i386_x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64).
/opt/homebrew/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3+4/ios/Classes/SwiftZoomPlugin.swift:3:8: error: no such module 'MobileRTC'
    import MobileRTC
           ^
/opt/homebrew/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3+4/ios/Classes/SwiftZoomPlugin.swift:3:8: error: no such module 'MobileRTC'
    import MobileRTC
           ^
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    warning: Capabilities for Signing & Capabilities may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the Runner editor. (in target 'Runner' from project 'Runner')
Could not build the application for the simulator.
Error launching application on iPhone 6.

Hello
That's my issue when i build on ios simulator (iOS 11.4). Can you help me?

**Comment by driftboat** [comment]
Did you execute this command `flutter pub run zoom:unzip_zoom_sdk` 
Duplicate of #14

**Comment by pinskynet** [comment]
I did but still got

**Comment by driftboat** [comment]
could you show me the console log when you execute that command, or check this: https://github.com/driftboat/flutter_zoom/issues/16#issuecomment-993305076

**Comment by pinskynet** [comment]
Here you are
`huy@Huys-Mac-mini example % flutter pub run zoom:unzip_zoom_sdk
Download https://www.dropbox.com/s/44rv7hgvqbgm7j7/MobileRTC?dl=1 to ../..//ios/MobileRTC.xcframework/ios-arm64_armv7/MobileRTC.framework/MobileRTC
Download https://www.dropbox.com/s/0qx52d1cb45oxku/MobileRTC?dl=1 to ../..//ios/MobileRTC.xcframework/ios-i386_x86_64-simulator/MobileRTC.framework/MobileRTC
Download https://www.dropbox.com/s/lcjoc2evrmeucte/commonlib.aar?dl=1 to ../..//android/libs/commonlib.aar
Download https://www.dropbox.com/s/exe1aa0aflyh53f/mobilertc.aar?dl=1 to ../..//android/libs/mobilertc.aar
Complete
huy@Huys-Mac-mini example % `

**Comment by driftboat** [comment]
could you show me the zoom uri_root in package_config.json
![image](https://user-images.githubusercontent.com/247809/148490348-f2058902-c1e7-4073-8e61-a911c15d0ded.png)

**Comment by driftboat** [comment]
I will check it, Or download these packages from webbrower and place them under the rootUri as https://github.com/driftboat/flutter_zoom/issues/16#issuecomment-993305076

**Comment by pinskynet** [comment]
i will try. thanks many

**Comment by driftboat** [comment]
Sorry! I don’t get this problem on my Mac,  You can check it by  adding some logs  in /opt/homebrew/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/zoom-1.0.3+4/bin/unzip_zoom_sdk.dart on your Mac.
The "rootUri" on your mac is very weird..., for me， It  looks like this ` "rootUri": "file:///Users/yxxiong/.pub-cache/hosted/pub.flutter-io.cn/zoom-1.0.3+4"`

**Comment by pinskynet** [comment]
Could you tell me flutter, xcode, ios version you build?

**Comment by driftboat** [comment]
Could you try this: https://stackoverflow.com/questions/67719774/cannot-run-flutter-app-in-ios-simulator-warning-cp-unable-to-find-matching

**Comment by pinskynet** [comment]
I will try. Thank you so much

**Comment by driftboat** [comment]
Sorry,It doesn't work, for now I have no idea to fix this issue, You can check this: https://github.com/flutter/flutter/issues/66104

**Comment by pinskynet** [comment]
No problem. Thanks for the enthusiasm.

**Comment by EyMaddis** [comment]
@pinskynet I assume that you are using an M1 based Mac (based on the fact that you use a Mac Mini). Could that be?

Run `flutter pub run zoom:unzip_zoom_sdk` and try on a real device.

If that works, you can also try the simulator again. 

Without knowing too much about the different .zip files, I think the `dev` version is for x86 (Intel) and the other version is for ARM based processors (Intel).

Edit:
I think I am right.
From your Logs: 
> Unable to find matching .xcframework slice in 'ios-i386_**x86_64**-simulator ios-arm64_armv7' for the current build architectures (**arm64** x86_64).

You could also try [this](https://github.com/firebase/firebase-ios-sdk/issues/6520#issuecomment-735412859) workaround.
